global:
  scrape_interval: 3s
  evaluation_interval: 3s

  external_labels:
    monitor: 'traefik'

rule_files:
  # - "first.rules"
  # - "second.rules"
  #
scrape_configs:
- job_name: 'node'
  static_configs:
    - targets: ['traefik:8080']

- job_name: 'prometheus'
  static_configs:
    - targets: ['prometheus:9090']

# TODO - Fix error against endpoint - https://prometheus.localhost/targets
- job_name: 'api'
  metrics_path: '/status/'
  static_configs:
    - targets: ['wallet.localhost:80']